### ISSUE TITLE
Create about page

### ISSUE THREAD

**Issue by bloodfued12** [fr3lancer17/Hungerism#5]
Creating the About page will require details for the user to find out why exactly the project was made.
To do this we will need to:
- [x] create html page 
- [x] create header details
- [x] create body
- [x] inside the body create the head, main and footer elements
- [x] within the Head element create H1, img, and nav elements
- [x] within the main element create img, p, h2, h3 elements for main content of the page 
- [x] within the footer element create anchor links to relevant pages and reference pages for the works that are attributed.

![Image](https://github.com/bloodfued12/Hungerism/assets/145117239/3a64ed58-451f-4d02-bddf-f09e9c57fafb)

**Comment by Kurresailakshmareddy** [comment]
about page is pushed to the Add-HTML branch
